version: "2"
plugins:
  phpcodesniffer:
    enabled: true
    phan:
      enabled: true
      config:
        file_extensions: "php"
    sonar-php:
      enabled: true
      tests:
        - tests/**
exclude_patterns:
- "tests/"
- "spec/"
- "**/vendor/"
