version: "2"
checks:
  similar-code:
    enabled: true
    config:
      threshold: #language-specific defaults. overrides affect all languages.
plugins:
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      ignore_warnings: true
      standard: "./phpcs.xml"
exclude_patterns:
  - "database/"
  - "config/"
  - "routes/"
  - "tests/"
  - "spec/"
  - "**/vendor/"
  - "resources/lang"
