language: php
sudo: false
cache:
  directories:
    - $HOME/.composer/cache/files
env:
  - APP_ENV=testing
php:
  - '7.3'
install: make setup
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - make lint
  - make analyse
  - make test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
