version: '3.7'

services:
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: homestead
            POSTGRES_USER: homestead
        ports:
            - 54320:5432
