version: '3.7'

services:
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
        ports:
            - 54320:5432
