version: '3.7'

services:
    php:
        build: ./docker/php
        ports:
            - 9000:9000
        volumes:
            - ./:/srv/www/app
            - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
        environment:
            MYSQL_USER: sicp
            MYSQL_PASSWORD: test
        networks:
            - default

    nginx:
        image: nginx
        ports:
            - 80:80
        volumes:
            - ./:/srv/www/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - default

    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: test
            POSTGRES_DB: db_sicp
            POSTGRES_USER: sicp
        ports:
            - 5432:5432
        networks:
            - default

    adminer:
        image: adminer
        links:
            - db:db
        ports:
            - 8081:8080
