name: CI

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches-ignore:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run CI
        run: make ci
