name: CI

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches-ignore:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: satackey/action-docker-layer-caching@v0.0.11

      - name: Run CI
        run: make ci
